### ISSUE TITLE
Make sure General Scattering Tutorial applies

### ISSUE THREAD

**Issue by lucas-wilkins** [SasView/tutorials#7]
Make sure the general scattering calculator tutorial is correct. Someone mentioned that the linked paper was incorrect. It might extend further too.

**Comment by butlerpd** [comment]
@smk78 and @lucas-wilkins .... I don't see a tutorial for the General Scattering Calculator? Is this referring instead to the GSC documentation? Our documentation usually follows the sequence: what is it, what is the maths, how to use. This last could be thought of as tutorial maybe? the difference is this normally just walks through usage and what the buttons mean and more of what I'd call a "quick start guide." while our tutorials are really tutorial in nature including exercises with real data? 

Just trying to clean up our issues in preparation for Contributor Camp XII hence the questions.

**Comment by smk78** [comment]
I've just built sas_calculator_help and had a look at it. @rjbourne made some extensive changes in Sep '21 and did a good job IMHO. Both references appear valid and the links to them work. So I'm a bit perplexed by what this issue is referring to. In any event, opening issues based on unattributed hearsay does not seem reasonable so I'm going to close this. In any event, @yunliu01 & co-workers are making further changes at the current Contributor Camp, so the doc will get another set of eyes on.
